#include <REGX52.H>
#include <IIC.H>

#define AT24C02_ADDRESS 0XA0

void AT24C02_SEND(unsigned char WORDADRESS,DATA)
{
	IIC_STAR();
	IIC_SEND_BYTE(AT24C02_ADDRESS);
	IIC_RESIVE_ASK();	
	IIC_SEND_BYTE(WORDADRESS);
	IIC_RESIVE_ASK();	
	IIC_SEND_BYTE(DATA);
	IIC_RESIVE_ASK();	
	IIC_STOP();
}

unsigned char AT24C02_REDBYTE(unsigned char WORDADRESS)
{
	unsigned char DATA;
	IIC_STAR();
	IIC_SEND_BYTE(AT24C02_ADDRESS);
	IIC_RESIVE_ASK();	
	IIC_SEND_BYTE(WORDADRESS);
	IIC_RESIVE_ASK();	
	IIC_STAR();
	IIC_SEND_BYTE(AT24C02_ADDRESS&0x01);
	IIC_RESIVE_ASK();
	DATA=IIC_RESIVE_BYTE();
	IIC_SEND_ACK(1);
	IIC_STOP();
	return DATA;
}