#include <REGX52.H>
#include <one wire.H>

#define DS18B20_SKIP_ROM     		0XCC
#define DS18B20_CONVERT_T    		0X44
#define DS18B20_READ_SCRATCHPAD     0XCC

void DS18B20_CONVERT()
{
	ONE_WIRE_INIT();
	ONE_WIRE_SEND_BYTE(DS18B20_SKIP_ROM);
	ONE_WIRE_SEND_BYTE(DS18B20_CONVERT_T);	
}	

float DS18B20_READT()
{
	float T;
	unsigned char TLSB,TMSB;
	int TM;
	ONE_WIRE_INIT();
	ONE_WIRE_SEND_BYTE(DS18B20_SKIP_ROM);
	ONE_WIRE_SEND_BYTE(DS18B20_READ_SCRATCHPAD);	
	TLSB=ONE_WIRE_RECIVE_BYTE();
	TMSB=ONE_WIRE_RECIVE_BYTE();
	TM=(TMSB<<8)|TLSB;
	T=(TM/16.0);
	return T;
}


